website/email_templates/views.py
from flask import render_template, Blueprint, request, session, current_app
import logging

logger = logging.getLogger('views')
email = Blueprint('email',__name__,template_folder="templates",static_folder="static")
    
@email.before_request
def send_session():
    session_log = {"Session Log" : [{"request": request.url},{"user_agent": str(request.user_agent)},{"proxy_ip": request.remote_addr}]}
    session["ip"] = request.headers.get("X_REAL_IP")
    session["log"] = (session_log)
    current_app.logger.debug(session)

@email.route('/', methods=('GET', 'POST'))
def index():
    return render_template("email_templates/layouts/index.html")

@email.route('/template/tobi', methods=('GET', 'POST'))
def templte_one():
    return render_template("email_templates/emails/email_base.html")

@email.route('/template/naruto_x_tmnt', methods=('GET', 'POST'))
def templte_two():
    return render_template("email_templates/emails/naruto_x_tmnt_abandoned_cart.html")

website/main/views.py
from flask import render_template, Blueprint, request, flash, session, current_app
import json

from ..email import check_email
from ..forms import Contact_Me

home = Blueprint('home',__name__,url_prefix="/")

@home.before_request
def send_session():
    session_log = {"Session Log" : [{"request": request.url},{"user_agent": str(request.user_agent)},{"proxy_ip": request.remote_addr}]}
    session["ip"] = request.headers.get("X_REAL_IP")
    session["log"] = (session_log)
    current_app.logger.debug(json.dumps(
    [{"request": request.url},
    {"user_agent": str(request.user_agent)},
    {"proxy_ip": request.remote_addr},
    {"forwarded_for": request.headers.get("X_FORWARDED_FOR", default=None)}, 
    {"real_ip": request.headers.get("X_REAL_IP", default=None)}, 
    {"host": request.headers.get("HOST", default=None)}]
    ))
    
@home.route('/', methods=('GET', 'POST'))
def homepage():
    form = Contact_Me()
    response = None
    if request.method == "POST":
        if form.validate_on_submit():
            response = check_email(form.name.data, form.textarea.data, form.email.data, form.test.data)
            response_log = {
            "response": response,
            "name": form.name.data,
            "email_msg": form.textarea.data,
            "email": form.email.data,}
            current_app.logger.debug(response_log)
        else:
            response = "There seems to be an error with your connection" ,"error"
            response_log = {
            "response": response,
            "name": form.name.data,
            "email_msg": form.textarea.data,
            "email": form.email.data,}
            current_app.logger.error(response_log)
        session["name"] = form.name.data
        session["email"] = form.email.data
        flash(response)
        print(response)
        return render_template("main/main.html", form=form, response=response)
    return render_template("main/main.html", form=form, response=response)

@home.route('/portfolio', methods=('GET', 'POST'))
def portfolio():
    return render_template("main/menu_grid.html")

@home.route('/styles', methods=('GET', 'POST'))
def styles():
    return render_template("main/styles.html")

#redirects
@home.route('/TexasToms', methods=('GET', 'POST'))
def texas_toms():
    return render_template("texas_toms/texas_toms.html")

website/parcel_viewer/views.py
from flask import render_template, Blueprint, request, session, current_app, jsonify, make_response
from flask_cors import cross_origin
import logging

from .parcel_data import Parcel

logger = logging.getLogger('views')
parcel_viewer = Blueprint('parcel_viewer',__name__,static_folder="static",template_folder="templates")

@parcel_viewer.route("/maps")
def maps():
    logging.warn("parcel_viewer/maps.html")
    return render_template("parcel_viewer/maps.html")


@parcel_viewer.route("/search", methods=['POST', 'GEt'])
@cross_origin()
def search():
    data = request.args.get('address_input')
    logging.warn(data)
    
    if data:
        response_message = Parcel().search(data)
    else: 
        response_message = [
            {"id":"", "multipolygon": "", "address": ""}
        ]
    response = make_response(render_template("parcel_viewer/search_results.html", results=response_message))
    response.headers["Referrer-Policy"] = "unsafe-url"
    return response

@parcel_viewer.route("/results/<addressID>", methods=['POST', 'GET'])
@cross_origin()
def results_(addressID):
    query = addressID
    logging.warn(addressID)
    if query:
        result = Parcel().viewer(query)
        return render_template("parcel_viewer/parcel_results.html", results=result)
    return render_template("parcel_viewer/parcel_results.html")

website/pixel_art/views.py
from flask import render_template, Blueprint, request, session, current_app
import logging, os, json

logger = logging.getLogger('views')
pixel_art = Blueprint('pixel_art',__name__,template_folder="templates",static_folder="static")
    
@pixel_art.before_request
def send_session():
    session_log = {"Session Log" : [{"request": request.url},{"user_agent": str(request.user_agent)},{"proxy_ip": request.remote_addr}]}
    session["ip"] = request.headers.get("X_REAL_IP")
    session["log"] = (session_log)
    current_app.logger.debug(session)

@pixel_art.route('/', methods=('GET', 'POST'))
def index():
    with open(os.path.abspath(os.path.join(".","website","pixel_art","images.json"))) as file:
        data = json.load(file)
        
    return render_template("pixel_art/pixel_art.html", imgs=data["images"])

website/texas_toms/views.py
from flask import render_template, Blueprint, request, session, current_app
import logging

logger = logging.getLogger('views')
texas_toms = Blueprint('texas_toms',__name__,template_folder="templates",static_folder="static")
    
@texas_toms.before_request
def send_session():
    session_log = {"Session Log" : [{"request": request.url},{"user_agent": str(request.user_agent)},{"proxy_ip": request.remote_addr}]}
    session["ip"] = request.headers.get("X_REAL_IP")
    session["log"] = (session_log)
    current_app.logger.debug(session)

@texas_toms.route('/', methods=('GET', 'POST'))
def index():
    return render_template("texas_toms/texas_toms.html")

website/templates/main/menu_grid.html
{% extends "layout/base.html"%}
{% from "macros/menu_grid_macro.html" import menucard%}
{% block title %}Tobi's Portfolio{% endblock %}
{% block head %}
<link rel="stylesheet" href="{{url_for('static', filename='main/css/menu_grid.css')}}">
{% endblock %}

{% block content %}

<section class="portfolio_title">
    <article>
        <h1>Portfolio Projects</h1>
        <p></p>
    </article>
</section>

<section class="grid_cards">
    {{menucard("Chat App", "Small Chat App made with the Flask Framework and WebSockets.",technologies= ["Python", "WebSockets", "Flask","JavaScript"], link=url_for('chat_app.index'),image=url_for('static', filename='main/images/chat_app_placeholder.png'))}}
    {{menucard("Parcel Viewer", "A searchable database UI for 2020 Kansas City Land Bank's Real Estate inventory.",technologies= ["Python", "Open Street Map API", "LeaFlet API", "Flask", "JavaScript"], link=url_for('parcel_viewer.maps'), image=url_for('static', filename='main/images/parcel_viewer_placeholder_small.png'))}}
    {{menucard("JavaScript Counter", "A simple JavaScript incremental counter.",technologies= ["HTML", "CSS", "JavaScript"],image=url_for('static', filename='main/images/counter_placeholder.png'))}}
    {{menucard("Email Templates", "Email Template Gallery.",technologies= ["HTML", "Inline CSS"],link=url_for('email.index'),image=url_for('static', filename='main/images/email_thumbnail.png'))}}
    {{menucard("Texas Toms", "A redesign for a local restaurants website.",technologies= ["HTML", "Inline CSS"], link=url_for('texas_toms.index'), image=url_for('static', filename='main/images/texas_toms_placeholder.png'))}}
    {{menucard("Pixel Art", "Art that I use for developer projects and also for fun.", link=url_for('pixel_art.index'), image=url_for('static', filename='main/images/PixelArt Thumbnail.png'))}}
</section>

{% endblock %}

website/templates/main/styles.html
{% extends "layout/base.html"%}
{% block title %}Modules{% endblock %}
{% block head %}
<link rel="stylesheet" href="{{url_for('static', filename='css/landing_page/modules.css')}}">
{% endblock %}

{% block content %}
<H1 style="grid-column: 1/-1">
    Styles
</H1>
{% endblock %}