website/main/views.py
from flask import render_template, Blueprint, request, flash, session, current_app
import json

from ..email import check_email
from ..forms import Contact_Me

home = Blueprint('home',__name__,url_prefix="/")

@home.before_request
def send_session():
    session_log = {"Session Log" : [{"request": request.url},{"user_agent": str(request.user_agent)},{"proxy_ip": request.remote_addr}]}
    session["ip"] = request.headers.get("X_REAL_IP")
    session["log"] = (session_log)
    current_app.logger.debug(json.dumps(
    [{"request": request.url},
    {"user_agent": str(request.user_agent)},
    {"proxy_ip": request.remote_addr},
    {"forwarded_for": request.headers.get("X_FORWARDED_FOR", default=None)}, 
    {"real_ip": request.headers.get("X_REAL_IP", default=None)}, 
    {"host": request.headers.get("HOST", default=None)}]
    ))
    
@home.route('/', methods=('GET', 'POST'))
def homepage():
    form = Contact_Me()
    response = None
    if request.method == "POST":
        if form.validate_on_submit():
            response = check_email(form.name.data, form.textarea.data, form.email.data, form.test.data)
            response_log = {
            "response": response,
            "name": form.name.data,
            "email_msg": form.textarea.data,
            "email": form.email.data,}
            current_app.logger.debug(response_log)
        else:
            response = "There seems to be an error with your connection" ,"error"
            response_log = {
            "response": response,
            "name": form.name.data,
            "email_msg": form.textarea.data,
            "email": form.email.data,}
            current_app.logger.error(response_log)
        session["name"] = form.name.data
        session["email"] = form.email.data
        flash(response)
        print(response)
        return render_template("main/main.html", form=form, response=response)
    return render_template("main/main.html", form=form, response=response)

@home.route('/portfolio', methods=('GET', 'POST'))
def portfolio():
    return render_template("main/menu_grid.html")

@home.route('/styles', methods=('GET', 'POST'))
def styles():
    return render_template("main/styles.html")

#redirects
@home.route('/TexasToms', methods=('GET', 'POST'))
def texas_toms():
    return render_template("texas_toms/texas_toms.html")

website/parcel_viewer/views.py
from flask import render_template, Blueprint, request, session, current_app, jsonify, make_response
from flask_cors import cross_origin
import logging

from .parcel_data import Parcel

logger = logging.getLogger('views')
parcel_viewer = Blueprint('parcel_viewer',__name__,static_folder="static",template_folder="templates")

@parcel_viewer.route("/maps")
def maps():
    logging.warn("parcel_viewer/maps.html")
    return render_template("parcel_viewer/maps.html")


@parcel_viewer.route("/search", methods=['POST', 'GEt'])
@cross_origin()
def search():
    data = request.args.get('address_input')
    logging.warn(data)
    
    if data:
        response_message = Parcel().search(data)
    else: 
        response_message = [
            {"id":"", "multipolygon": "", "address": ""}
        ]
    response = make_response(render_template("parcel_viewer/search_results.html", results=response_message))
    response.headers["Referrer-Policy"] = "unsafe-url"
    return response

@parcel_viewer.route("/results/<addressID>", methods=['POST', 'GET'])
@cross_origin()
def results_(addressID):
    query = addressID
    logging.warn(addressID)
    if query:
        result = Parcel().viewer(query)
        return render_template("parcel_viewer/parcel_results.html", results=result)
    return render_template("parcel_viewer/parcel_results.html")

website/pixel_art/views.py
from flask import render_template, Blueprint, request, session, current_app
import logging, os, json

logger = logging.getLogger('views')
pixel_art = Blueprint('pixel_art',__name__,template_folder="templates",static_folder="static")
    
@pixel_art.before_request
def send_session():
    session_log = {"Session Log" : [{"request": request.url},{"user_agent": str(request.user_agent)},{"proxy_ip": request.remote_addr}]}
    session["ip"] = request.headers.get("X_REAL_IP")
    session["log"] = (session_log)
    current_app.logger.debug(session)

@pixel_art.route('/', methods=('GET', 'POST'))
def index():
    with open(os.path.abspath(os.path.join(".","website","pixel_art","images.json"))) as file:
        data = json.load(file)
        
    return render_template("pixel_art/pixel_art.html", imgs=data["images"])

website/texas_toms/views.py
from flask import render_template, Blueprint, request, session, current_app
import logging

logger = logging.getLogger('views')
texas_toms = Blueprint('texas_toms',__name__,template_folder="templates",static_folder="static")
    
@texas_toms.before_request
def send_session():
    session_log = {"Session Log" : [{"request": request.url},{"user_agent": str(request.user_agent)},{"proxy_ip": request.remote_addr}]}
    session["ip"] = request.headers.get("X_REAL_IP")
    session["log"] = (session_log)
    current_app.logger.debug(session)

@texas_toms.route('/', methods=('GET', 'POST'))
def index():
    return render_template("texas_toms/texas_toms.html")

website/templates/layout/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="manifest" href="{{ url_for('static', filename='manifest.json')}}" />

    <link rel="shortcut icon" href="{{ url_for('static', filename='layout/images/icon/White Outline Logo Mark.ico')}}">

    <link rel="preload" href="{{url_for('static', filename='main/css/style.css')}}" as="style">
    <link rel="stylesheet" href="{{url_for('static', filename='main/css/style.css')}}">

    <link rel="preload" href="{{url_for('static', filename='main/images/White Candice Tobi.png')}}" as="image" type="image/png">
    <title>{% block title %}Base{% endblock %}</title>
    {% block head %}{% endblock %}
</head>
<body>
    <script>0</script>
    <nav>
        <div class="nav_margin">
            <div class="logo_wrapper">
                {% block logo_link %}
                <a href="{{url_for('home.homepage')}}">
                    <img src="{{url_for('static', filename='main/images/White Candice Tobi.png')}}">
                </a>
                {% endblock %}
            </div>

            <div class="nav_links">
                <ul>
                    <li class="home_nav">{% block portfolio_link %}<a href="{{url_for('home.portfolio')}}"><span>Portfolio</span></a>{% endblock %}</li>
                    <li class="about_me_nav">{% block aboutme_link %}<a href="{{url_for('home.homepage')}}#about_me"><span>About Me</span></a>{% endblock %}</li>
                    <li class="contact_me_nav">{% block contactme_link %}<a href="{{url_for('home.homepage')}}#contact_me"><button>Contact Me</button></a>{% endblock %}</li>
                </ul> 
            </div>
        </div>
    </nav>
    <main>
    {% block content %}
    
    {% endblock %}
    </main>
    <footer class="footer">
        <div class="foot_wrapper footer1">
            <ul>
                <li class="filled"><h4><a href="{{url_for('home.homepage')}}">Home Page</a></h4></li>
                <li class="filled"><p><a href="{{url_for('home.homepage')}}#about_me">About Me</a></p></li>
                <li class="filled"><p><a href="{{url_for('home.portfolio')}}">Portfolio</a></p></li>
                <li class="filled"><p><a href="https://asourkat.com" target="_blank" rel="noopener noreferrer">Sour Kat</a></h4></li>
                <li class="filled"><p><a href="{{url_for('pixel_art.index')}}">Pixel Art</a></h4></li>
                <li class="filled"><p><a href="{{url_for('javascript_counter.index')}}">JavaScript Counter</a></h4></li>
            </ul>
        </div>
        <div class="foot_wrapper footer2">
            <ul>
                <li class="filled"><p><a href="{{url_for('chat_app.index')}}">Chat App</a></h4></li>
                <li class="filled"><p><a href="{{url_for('texas_toms.index')}}">Texas Toms</a></h4></li>
                <li class="filled"><p><a href="{{url_for('parcel_viewer.maps')}}">Parcel Viewer</a></h4></li>
                <li class="filled"><p><a href="{{url_for('email.index')}}">Email Templates</a></h4></li>
                <li></li>
                <li></li>
            </ul>
        </div>
        <div class="foot_wrapper footer3">
            <ul>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>

            </ul>
        </div>
        <div class="foot_wrapper footer4">
            <ul>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>

            </ul>
        </div>
    </footer>
</body>
</html>